import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import ReduxProvider from '../providers/redux-provider'
import { cookies } from 'next/headers' // Import cookies from Next.js
import LanguageSelect from '@/components/LanguageSelect'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LanguageSelect/>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}