import type { Metadata } from 'next'
import './globals.css'
import ReduxProvider from './providers/redux-provider'
import LanguageSelect from '@/app/components/LanguageSelect'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body className={`antialiased`}>
        <LanguageSelect/>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}